# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml


#trigger:
#- main

#pool:
#  vmImage: ubuntu-latest

#steps:
#- script: echo Hello, world!
#  displayName: 'Run a one-line script'

#- script: |
#    echo Add other tasks to build, test, and deploy your project.
#    echo See https://aka.ms/yaml
#  displayName: 'Run a multi-line script'


trigger: 
- main 
 
pool: 
  vmImage: 'ubuntu-latest' 
 
steps: 
 
- task: UseDotNet@2 

  inputs: 
    packageType: 'sdk' 
    version: '8.0.x' 


- script: dotnet restore 
  displayName: Restore Packages 
 
- script: dotnet build 
  displayName: Build Project 
 
- script: pwsh bin/Debug/net8.0/playwright.ps1 install 
  displayName: Install Playwright Browsers 
 
- script: dotnet test 
  displayName: Run Testss 

 